## Reading data from different sources

In [20]:
import pandas as pd

### JSON

In [21]:
from io import StringIO
import pandas as pd

# JSON data with two records (list of dicts)
json_data = '''
[
  {"id": 101, "name": "Alice", "department": "Engineering",
   "skills": ["Python", "Pandas", "SQL", "Machine Learning"]},
  {"id": 102, "name": "Bob", "department": "Marketing",
   "skills": ["Excel", "SEO", "Content Writing"]}
]
'''

# Convert string into a file-like object
string_data = StringIO(json_data)

# Read into pandas DataFrame
df = pd.read_json(string_data)
print(df)

    id   name   department                                   skills
0  101  Alice  Engineering  [Python, Pandas, SQL, Machine Learning]
1  102    Bob    Marketing            [Excel, SEO, Content Writing]

In [22]:
# Converting back to json
# It adds index to each value for a column

df.to_json()

'{"id":{"0":101,"1":102},"name":{"0":"Alice","1":"Bob"},"department":{"0":"Engineering","1":"Marketing"},"skills":{"0":["Python","Pandas","SQL","Machine Learning"],"1":["Excel","SEO","Content Writing"]}}'

In [23]:
# Using orient as index
# We will get each row as a value for index

df.to_json(orient='index')

'{"0":{"id":101,"name":"Alice","department":"Engineering","skills":["Python","Pandas","SQL","Machine Learning"]},"1":{"id":102,"name":"Bob","department":"Marketing","skills":["Excel","SEO","Content Writing"]}}'

In [24]:
# Using orient as records
# We will get each row as an element in list

df.to_json(orient='records')

'[{"id":101,"name":"Alice","department":"Engineering","skills":["Python","Pandas","SQL","Machine Learning"]},{"id":102,"name":"Bob","department":"Marketing","skills":["Excel","SEO","Content Writing"]}]'

### CSV

In [25]:
df_with_header = pd.read_csv('employees.csv')
df_with_header.head()

   id     name   age   department   salary
0   1    Alice  25.0           HR  50000.0
1   2      Bob  30.0  Engineering  70000.0
2   3  Charlie  28.0    Marketing  55000.0
3   4    Diana  35.0  Engineering  80000.0
4   5    Ethan  40.0      Finance  90000.0

In [26]:
df_without_header = pd.read_csv('employees.csv',header=None)
df_without_header.head()

    0        1    2            3       4
0  id     name  age   department  salary
1   1    Alice   25           HR   50000
2   2      Bob   30  Engineering   70000
3   3  Charlie   28    Marketing   55000
4   4    Diana   35  Engineering   80000

### HTML

In [27]:
!pip install lxml html5lib beautifulsoup4

In [28]:
url = 'https://www.fdic.gov/resources/resolutions/bank-failures/failed-bank-list/'
df = pd.read_html(url)
df

[                                            Bank Name                City  \
 0                   Metropolitan Capital Bank & Trust             Chicago
 1                        The Santa Anna National Bank          Santa Anna
 2                                Pulaski Savings Bank             Chicago
 3                  The First National Bank of Lindsay             Lindsay
 4               Republic First Bank dba Republic Bank        Philadelphia
 5                                       Citizens Bank            Sac City
 6                            Heartland Tri-State Bank             Elkhart
 7                                 First Republic Bank       San Francisco
 8                                      Signature Bank            New York
 9                                 Silicon Valley Bank         Santa Clara
 10                                  Almena State Bank              Almena
 11                         First City Bank of Florida   Fort Walton Beach
 12                               The First State Bank       Barboursville
 13                                 Ericson State Bank             Ericson
 14                   City National Bank of New Jersey              Newark
 15                                      Resolute Bank              Maumee
 16                              Louisa Community Bank              Louisa
 17                               The Enloe State Bank              Cooper
 18                Washington Federal Bank for Savings             Chicago
 19    The Farmers and Merchants State Bank of Argonia             Argonia
 20                                Fayette County Bank          Saint Elmo
 21  Guaranty Bank, (d/b/a BestBank in Georgia & Mi...           Milwaukee
 22                                     First NBC Bank         New Orleans
 23                                      Proficio Bank  Cottonwood Heights
 24                      Seaway Bank and Trust Company             Chicago

             State   Cert                Acquiring Institution  \
 0        Illinois  57488              First Independence Bank
 1           Texas   5520            Coleman County State Bank
 2        Illinois  28611                      Millennium Bank
 3        Oklahoma   4134               First Bank & Trust Co.
 4    Pennsylvania  27332    Fulton Bank, National Association
 5            Iowa   8758            Iowa Trust & Savings Bank
 6          Kansas  25851               Dream First Bank, N.A.
 7      California  59017            JPMorgan Chase Bank, N.A.
 8        New York  57053                  Flagstar Bank, N.A.
 9      California  24735  First–Citizens Bank & Trust Company
 10         Kansas  15426                          Equity Bank
 11        Florida  16748            United Fidelity Bank, fsb
 12  West Virginia  14361                       MVB Bank, Inc.
 13       Nebraska  18265           Farmers and Merchants Bank
 14     New Jersey  21111                      Industrial Bank
 15           Ohio  58317                   Buckeye State Bank
 16       Kentucky  58112    Kentucky Farmers Bank Corporation
 17          Texas  10716                   Legend Bank, N. A.
 18       Illinois  30570                   Royal Savings Bank
 19         Kansas  17719                          Conway Bank
 20       Illinois   1802            United Fidelity Bank, fsb
 21      Wisconsin  30003  First-Citizens Bank & Trust Company
 22      Louisiana  58302                         Whitney Bank
 23           Utah  35495                    Cache Valley Bank
 24       Illinois  19328                  State Bank of Texas

          Closing Date  Fund  Sort ascending
 0    January 30, 2026                 10550
 1       June 27, 2025                 10549
 2    January 17, 2025                 10548
 3    October 18, 2024                 10547
 4      April 26, 2024                 10546
 5    November 3, 2023                 10545
 6       July 28, 2023                 10544
 7         May 1, 2023                 10543
 8      March 12, 2023                 10540
 9      March 10, 2023                 10539
 10   October 23, 2020                 10538
 11   October 16, 2020                 10537
 12      April 3, 2020                 10536
 13  February 14, 2020                 10535
 14   November 1, 2019                 10534
 15   October 25, 2019                 10533
 16   October 25, 2019                 10532
 17       May 31, 2019                 10531
 18  December 15, 2017                 10530
 19   October 13, 2017                 10529
 20       May 26, 2017                 10528
 21        May 5, 2017                 10527
 22     April 28, 2017                 10526
 23      March 3, 2017                 10525
 24   January 27, 2017                 10524  ]

In [29]:
df[0].head()

,Bank Name,City,State,Cert,Acquiring Institution,Closing Date,Fund Sort ascending
0,Metropolitan Capital Bank & Trust,Chicago,Illinois,57488,First Independence Bank,"January 30, 2026",10550
1,The Santa Anna National Bank,Santa Anna,Texas,5520,Coleman County State Bank,"June 27, 2025",10549
2,Pulaski Savings Bank,Chicago,Illinois,28611,Millennium Bank,"January 17, 2025",10548
3,The First National Bank of Lindsay,Lindsay,Oklahoma,4134,First Bank & Trust Co.,"October 18, 2024",10547
4,Republic First Bank dba Republic Bank,Philadelphia,Pennsylvania,27332,"Fulton Bank, National Association","April 26, 2024",10546