### Handling imbalanced dataset

If there is a dataset with majority of data points belonging to a single class then using that data to train can make model biased towards majority class i.e if a data set contains 1000 data points with 900 belonging to class A and 100 belonging to class B, then the model will be biased towards labeling data points to class A

In [1]:
import numpy as np 
import pandas as pd

In [2]:
# Set the random seed for reproducibility
np.random.seed(123)

# Create a dataframe with 2 classes
n_samples = 1000
class_0_ratio = 0.9
n_class_0 = int(n_samples * class_0_ratio)
n_class_1 = n_samples - n_class_0

In [3]:
n_class_0,n_class_1

(900, 100)

In [5]:
# Creating dataframe with imbalanced dataset

class_0 = pd.DataFrame({
    'feature_1': np.random.normal(loc=0, scale=1, size=n_class_0),
    'feature_2': np.random.normal(loc=0, scale=1, size=n_class_0),
    'target': [0]*n_class_0
})

class_1 = pd.DataFrame({
    'feature_1': np.random.normal(loc=2, scale=1, size=n_class_1),
    'feature_2': np.random.normal(loc=2, scale=1, size=n_class_1),
    'target': [1]*n_class_1
})

In [7]:
df = pd.concat([class_1,class_0]).reset_index(drop=True)
df.head()

     feature_1  feature_2  target
995   0.792809  -1.561866       0
996  -2.030271  -0.767819       0
997  -1.880218   0.387223       0
998  -1.469470  -1.212918       0
999  -0.592608   2.018714       0

In [8]:
df['target'].value_counts()

target
0    900
1    100
Name: count, dtype: int64

#### Upsampling

To reduce the imbalance in the dataset, we increase the number of 1's (in this case) to get a balance between number of data points with class 1 and 0.

In [9]:
df_minority = df[df['target']==1]
df_majority = df[df['target']==0]

In [11]:
from sklearn.utils import resample

df_minority_upsampled = resample(df_minority, replace=True, n_samples=len(df_majority), random_state=42)
df_minority_upsampled

    feature_1  feature_2  target
51   2.305451   2.905343       1
92   2.954339   2.000977       1
14   3.790856   1.927957       1
71   1.731246   2.819483       1
60   1.305364   2.456515       1
..        ...        ...     ...
52   0.627095   1.766644       1
65   0.905984   1.527330       1
76   0.480405   2.463277       1
42   1.312561   2.930412       1
74   1.773316   1.866832       1

[900 rows x 3 columns]

In [13]:
df_upsampled = pd.concat([df_majority,df_minority_upsampled])
df_upsampled['target'].value_counts()

target
0    900
1    900
Name: count, dtype: int64

### Down sampling

In down sampling we will reduce the number of majority samples (number of data points with target 0 in this case)

In [14]:
# Creating dataframe with imbalanced dataset

class_0 = pd.DataFrame({
    'feature_1': np.random.normal(loc=0, scale=1, size=n_class_0),
    'feature_2': np.random.normal(loc=0, scale=1, size=n_class_0),
    'target': [0]*n_class_0
})

class_1 = pd.DataFrame({
    'feature_1': np.random.normal(loc=2, scale=1, size=n_class_1),
    'feature_2': np.random.normal(loc=2, scale=1, size=n_class_1),
    'target': [1]*n_class_1
})

In [23]:
df = pd.concat([class_0,class_1]).reset_index(drop=True)
df['target'].value_counts()

target
0    900
1    100
Name: count, dtype: int64

In [24]:
df_minority = df[df['target']==1]
df_majority = df[df['target']==0]

In [25]:
df_majority_downsampled = resample(
    df_majority, replace=False,
    n_samples=len(df_minority),
    random_state=42
)
df_majority_downsampled.shape

(100, 3)

In [28]:
df_downsampled = pd.concat([df_majority,df_minority_upsampled])
df_downsampled['target'].value_counts()

target
0    900
1    900
Name: count, dtype: int64