### Target Guided Ordinal Encoding

It is a technique used to encode categorical variables based on their relationship with the target variable. This encoding technique is useful when we have a categorical variable with a large number of unique categories, and we want to use this variable as a feature in our machine learning model.

In target guided encoding, we replace each category in the categorical variable with a numerical value based on the mean or median of the target variable for that category. This creates a monotonic relationship between the categorical variable and the target variable, which can improve the predictive power of our model.

In [1]:
import pandas as pd

In [2]:
df = pd.DataFrame({
    'city': ['New York','London','New York','Tokyo', 'New York', 'Paris'],
    'price': [200,150,300,250,180,32]
})

In [4]:
mean_price = df.groupby('city')['price'].mean().to_dict()
mean_price

{'London': 150.0,
 'New York': 226.66666666666666,
 'Paris': 32.0,
 'Tokyo': 250.0}

In [6]:
# We will encode city names with their mean
# The categorical values (cities) will be replaced by their mean

df['city_encoded'] = df['city'].map(mean_price)
df

       city  price  city_encoded
0  New York    200    226.666667
1    London    150    150.000000
2  New York    300    226.666667
3     Tokyo    250    250.000000
4  New York    180    226.666667
5     Paris     32     32.000000

#### For a dataset

In [7]:
import seaborn as sns
df = sns.load_dataset('tips')
df.head()

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [9]:
grouped_time = df.groupby('time')['total_bill'].mean().to_dict()
grouped_time

{'Lunch': 17.168676470588235, 'Dinner': 20.79715909090909}

In [10]:
df['time_encoded'] = df['time'].map(grouped_time)
df.head()

   total_bill   tip     sex smoker  day    time  size time_encoded
0       16.99  1.01  Female     No  Sun  Dinner     2    20.797159
1       10.34  1.66    Male     No  Sun  Dinner     3    20.797159
2       21.01  3.50    Male     No  Sun  Dinner     3    20.797159
3       23.68  3.31    Male     No  Sun  Dinner     2    20.797159
4       24.59  3.61  Female     No  Sun  Dinner     4    20.797159